# Generated by Django 4.2.2 on 2024-01-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_foodviewed_view_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodviewed',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
